//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_buggy : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Steering
        {
            get
            {
                return SteamVR_Actions.buggy_Steering;
            }
        }
        
        public virtual SteamVR_Action_Boolean Pause
        {
            get
            {
                return SteamVR_Actions.buggy_Pause;
            }
        }
        
        public virtual SteamVR_Action_Skeleton vrrotation
        {
            get
            {
                return SteamVR_Actions.buggy_vrrotation;
            }
        }
    }
}
